name: infra-platform

version: "3.9"

services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    restart: unless-stopped
    ports:
      - "7072:7071"
    volumes:
      - ./config-repo:/config-repo
    environment:
      SPRING_PROFILES_ACTIVE: native
      CONFIG_REPO_LOCATION: file:/config-repo
    networks:
      - ms-net

  registry-server:
    build:
      context: ./registry-server
      dockerfile: Dockerfile
    container_name: registry-server
    restart: unless-stopped
    depends_on:
      - config-server
    ports:
      - "7082:7081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CONFIG_SERVER_URL: http://config-server:7071
    networks:
      - ms-net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    depends_on:
      - config-server
      - registry-server
    ports:
      - "7092:7091"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CONFIG_SERVER_URL: http://config-server:7071
    networks:
      - ms-net

networks:
  ms-net:
    #external: true
    name: ms-net