server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://mysql-service-request:3306/db_ms_service_request?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://registry-server:7081/eureka
